# This file was generated by GoReleaser. DO NOT EDIT.
cask "39claw" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/39claw/"
      sha256 "8667c6e421529257cb889cd6f75cb47029ee48c049f4350da9db4d6a30a383d9"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/39claw/"
      sha256 "1a8413125980a958d4227d4bfa3cb3b9b6ce81834390e7640a4a42e1fc115c00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/39claw/"
      sha256 "c81e9eb5ebccaa8d10622198955103c28f6e3f9aa1d64d70ae3ff54eb8d3805a"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/39claw/"
      sha256 "875e60cb0499794a567c920a2235f8b4f4a45c823929fcdfd42b01598d8abc55"
    end
  end

  name "39claw"
  desc "Discord bot that connects Discord conversations to Codex"
  homepage "https://github.com/HatsuneMiku3939/39claw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "39claw"

  # No zap stanza required

  caveats <<~EOS
    This cask installs an unsigned binary.

    If macOS blocks execution, remove the quarantine attribute manually:
      xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/39claw/1.0.0/39claw"

    Review the binary and command before bypassing Gatekeeper.
  EOS
end
