# This file was generated by GoReleaser. DO NOT EDIT.
cask "39claw" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "154df0fdf166f8d27f9df1bc6610f05b9d7d5364de86ff119767502ad8738401"
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/39claw/"
    end
    on_arm do
      sha256 "e8db3f24c6a960c84946eaa0f0c08d397b9c0107036f306545f98a0209a9fbba"
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/39claw/"
    end
  end

  on_linux do
    on_intel do
      sha256 "09d84e4e7908a3f4fbc4ffb4ce05e30555371c7a14f656a81264e335f1eefa9a"
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/39claw/"
    end
    on_arm do
      sha256 "bc167af14da0799dbed247f04dee8423ec0bf39956fcfdaaa2d8ac41b7aa9ccf"
      url "https://github.com/HatsuneMiku3939/39claw/releases/download/v#{version}/39claw_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/39claw/"
    end
  end

  name "39claw"
  desc "Discord bot that connects Discord conversations to Codex"
  homepage "https://github.com/HatsuneMiku3939/39claw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "39claw"

  # No zap stanza required

  caveats <<~EOS
    This cask installs an unsigned binary.

    If macOS blocks execution, remove the quarantine attribute manually:
      xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/39claw/1.1.0/39claw"

    Review the binary and command before bypassing Gatekeeper.
  EOS
end
