# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobsd" do
  version "0.9.1"

  on_macos do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "0d0a4fd139b80ce21c382d061e4fbf139191fda6c0ff8906f6cf8b24a6720532"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "10230e5513c44a8fabacaf15fd9abc4dda4618ba5044792a047b34764fae392f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "d2a642c689b55777485aa229cb30f00dd4bdad35c2a2f7eec9432727a73a79a7"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "e3e7ef438d49b9d63a0ccd7d13fff47fe6547ad6360d1fafa2a288f6fbdca4f4"
    end
  end

  name "jobsd"
  desc "Local, instance-oriented job scheduler backed by SQLite"
  homepage "https://github.com/HatsuneMiku3939/jobsd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobsd"

  # No zap stanza required

end
