# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobsd" do
  name "jobsd"
  desc "Local, instance-oriented job scheduler backed by SQLite"
  homepage "https://github.com/HatsuneMiku3939/jobsd"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobsd"

  on_macos do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "e3c777513407059353a5265f782028af1ba6dcc587b1bc920f30319c3f341dd6"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "f1af5444594ae7496c7727abf95b7aacc0e69fbca6493ff0548641e564a6148b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "3c78dab39d43af7118f829644bc04b3c4caeab56066963fa35dcc1b2dd96225d"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "ea458a1a09d1b531eb5baec0b0664a2cb45480e39970440cd78706fb877fdf7d"
    end
  end

  # No zap stanza required
end
