# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobsd" do
  name "jobsd"
  desc "Local, instance-oriented job scheduler backed by SQLite"
  homepage "https://github.com/HatsuneMiku3939/jobsd"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobsd"

  on_macos do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "d61c1ee029495e6314ea87d43367939d3caa75618108a4477483c9842183c5e1"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "5825bdb1d11f0216b5f899924d8dbf3e6ff1d9c88ba86dde83697862bb4b2cc3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "d10baae489c25a647bf190edb3d13c44bb5a2e1bca4d884bae98f931146d5dda"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/jobsd/releases/download/v#{version}/jobsd_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/jobsd/"
      sha256 "f1f43dcab95ec526579a156073c80b73f86e0b93c8a023b1a7e2120cb5149a0c"
    end
  end

  # No zap stanza required
end
