# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchbot-cli" do
  name "switchbot-cli"
  desc "CLI for SwitchBot devices"
  homepage "https://github.com/HatsuneMiku3939/switchbot-cli"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchbot-cli"

  on_macos do
    on_intel do
      url "https://github.com/HatsuneMiku3939/switchbot-cli/releases/download/v#{version}/switchbot-cli_#{version}_Darwin_x86_64.zip",
        verified: "github.com/HatsuneMiku3939/switchbot-cli/"
      sha256 "ff6efa7ede165a72bedef36a2f877b2dc46deae2e6800419f0a7487e1004749d"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/switchbot-cli/releases/download/v#{version}/switchbot-cli_#{version}_Darwin_arm64.zip",
        verified: "github.com/HatsuneMiku3939/switchbot-cli/"
      sha256 "424b757e5d443630601cf57b90aec3600416928eb6ba8f88df4d2b31d682a6b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HatsuneMiku3939/switchbot-cli/releases/download/v#{version}/switchbot-cli_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/HatsuneMiku3939/switchbot-cli/"
      sha256 "e8b27b575319520863060273ef4f4f4ac66dea6e5f7986e5a0358ebe7afc7bb5"
    end
    on_arm do
      url "https://github.com/HatsuneMiku3939/switchbot-cli/releases/download/v#{version}/switchbot-cli_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/HatsuneMiku3939/switchbot-cli/"
      sha256 "6c43a63a446115e5fd4b1a2cb4156e1dbb17cb42fe222fa45387623a4737f023"
    end
  end

  caveats do
    "This cask installs an unsigned binary."
    ""
    "If macOS blocks execution, remove the quarantine attribute manually:"
    "  xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/switchbot-cli/0.9.0/switchbot-cli""
    ""
    "Review the binary and command before bypassing Gatekeeper."
  end

  # No zap stanza required
end
